name: Trivy SBOM (CycloneDX)

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  trivy-sbom:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # 1) Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 3) Générer un SBOM CycloneDX avec Trivy
      - name: Generate SBOM with Trivy (CycloneDX)
        uses: aquasecurity/trivy-action@0.33.1
        with:
          command: 'sbom'
          scan-type: 'fs'
          scan-ref: '.'
          format: 'cyclonedx-json'
          output: 'sbom-trivy-cyclonedx.json'

      # 4) Uploader le SBOM en artifact
      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-trivy-cyclonedx
          path: sbom-trivy-cyclonedx.json
